//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home.models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Cosmetic : INotifyPropertyChanged
    {
        public static char COL_STATUS = 'A';
        public static char COL_ID = 'B';
        public static char COL_NAME = 'C';
        public static char COL_IMAGE_URL = 'D';
        public static char COL_PRICE = 'E';
        public static char COL_ORIGIN = 'F';
        public static char COL_DETAIL = 'G';

        private int status = 0;
        private int id;
        private int category;
        private string name;
        private string image = "default_cosmetic_icon.ico";
        private int price;
        private string origin = "---";
        private string detail = "---";

        public int Status
        {
            get => status;
            set
            {
                status = value;
                notifyPropertyChanged("Status");
            }
        }

        public int ID
        {
            get => id;
            set
            {
                id = value;
                notifyPropertyChanged("ID");
            }
        }

        public int Category
        {
            get => category;
            set
            {
                category = value;
                notifyPropertyChanged("Category");
            }
        }

        public string Name
        {
            get => name;
            set
            {
                name = value;
                notifyPropertyChanged("Name");
            }
        }

        public string Image
        {
            get => image;
            set
            {
                image = value;
                //notifyPropertyChanged("Image");
            }
        }

        public int Price
        {
            get => price;
            set
            {
                price = value;
                notifyPropertyChanged("Price");
            }
        }

        public string Origin
        {
            get => origin;
            set
            {
                origin = value;
                notifyPropertyChanged("Origin");
            }
        }

        public string Detail
        {
            get => detail;
            set
            {
                detail = value;
                notifyPropertyChanged("Detail");
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;

        private void notifyPropertyChanged(string name)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(name));
        }




        public virtual Category Category1 { get; set; }
    }
}
